# Generated by Django 2.2.24 on 2021-12-02 03:46

import django.db.models.deletion

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rapidsms", "0004_auto_20150801_2138"),
        ("smpp_gateway", "0002_mtmessage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="momessage",
            name="channel",
        ),
        migrations.RemoveField(
            model_name="mtmessage",
            name="channel",
        ),
        migrations.AddField(
            model_name="momessage",
            name="backend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rapidsms.Backend",
            ),
        ),
        migrations.AddField(
            model_name="mtmessage",
            name="backend",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rapidsms.Backend",
            ),
        ),
    ]
