# Generated by Django 2.2.24 on 2021-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smpp_gateway", "0003_auto_20211202_0546"),
    ]

    operations = [
        migrations.AlterField(
            model_name="momessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                ],
                max_length=32,
            ),
        ),
    ]
