# Generated by Django 2.2.24 on 2021-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smpp_gateway", "0004_auto_20211202_1839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("error", "Error"),
                ],
                max_length=32,
            ),
        ),
    ]
