# Generated by Django 4.2.13 on 2024-06-10 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smpp_gateway", "0005_alter_mtmessagestatus_command_status"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="momessage",
            index=models.Index(
                condition=models.Q(("status", "new")),
                fields=["status"],
                name="mo_message_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mtmessage",
            index=models.Index(
                condition=models.Q(("status", "new")),
                fields=["status"],
                name="mt_message_status_idx",
            ),
        ),
    ]
