# Generated by Django 4.2.13 on 2024-06-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smpp_gateway", "0006_message_status_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="momessage",
            name="error",
            field=models.TextField(blank=True, verbose_name="error"),
        ),
        migrations.AlterField(
            model_name="momessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("processing", "Processing"),
                    ("error", "Error"),
                    ("done", "Done"),
                ],
                max_length=32,
                verbose_name="status",
            ),
        ),
    ]
