# Generated by Django 4.2.16 on 2024-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smpp_gateway', '0007_momessage_error_alter_momessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtmessage',
            name='is_transactional',
            field=models.BooleanField(null=True),
        ),
    ]
