# Generated by Django 4.2.16 on 2024-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smpp_gateway", "0008_remove_mtmessage_mt_message_status_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mtmessage",
            name="error",
            field=models.TextField(blank=True, verbose_name="error"),
        ),
    ]
