# Generated by Django 4.2.16 on 2024-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smpp_gateway", "0008_mtmessage_is_transactional"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mtmessage",
            name="is_transactional",
        ),
        migrations.AddField(
            model_name="mtmessage",
            name="priority_flag",
            field=models.IntegerField(
                choices=[
                    (0, "Level 0 (lowest) priority"),
                    (1, "Level 1 priority"),
                    (2, "Level 2 priority"),
                    (3, "Level 3 (highest) priority"),
                ],
                null=True,
            ),
        ),
    ]
